#!/usr/bin/env bash
#
# Reads .env.private and writes the correct subset of variables
# to each worker's .dev.vars and to public-kb/.dev.vars.
#
# Usage: bash scripts/setup-env.sh [path-to-env-file]
#        Defaults to .env.private in the repo root.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${1:-.env.private}"

if [[ "$ENV_FILE" != /* ]]; then
  ENV_FILE="$REPO_ROOT/$ENV_FILE"
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Error: $ENV_FILE not found."
  echo "Copy .env.example to .env.private and fill in your values first."
  exit 1
fi

# Get a variable's value from the env file. Returns empty string if not found or empty.
get_var() {
  local key="$1"
  local val
  val=$(grep -m1 "^${key}=" "$ENV_FILE" 2>/dev/null | sed "s/^${key}=//") || true
  echo "$val"
}

# Write a .dev.vars file from a list of variable names
write_dev_vars() {
  local target="$1"
  shift
  local vars=("$@")

  mkdir -p "$(dirname "$target")"

  {
    echo "# Generated by scripts/setup-env.sh from .env.private"
    echo "# Re-run the script after changing .env.private"
    echo ""
    for var in "${vars[@]}"; do
      local val
      val="$(get_var "$var")"
      if [[ -n "$val" ]]; then
        echo "${var}=${val}"
      fi
    done
  } > "$target"

  local count
  count=$(grep -c '=' "$target" 2>/dev/null || echo 0)
  echo "  Wrote $target ($count vars)"
}

echo "Distributing variables from $ENV_FILE..."
echo ""

# ─── workers/crawl/.dev.vars ─────────────────────────────────────────
write_dev_vars "$REPO_ROOT/workers/crawl/.dev.vars" \
  CF_ACCOUNT_ID \
  CF_API_TOKEN \
  CRAWL_SECRET \
  PIPELINE_URL

# ─── workers/pipeline/.dev.vars ──────────────────────────────────────
write_dev_vars "$REPO_ROOT/workers/pipeline/.dev.vars" \
  KB_DOMAIN \
  INTERNAL_KB_DOMAIN \
  IMAGE_DOMAIN \
  MANAGER_PORTAL_URL \
  SOURCE_IMAGE_CDN \
  BRAND_NAME \
  CONNECT_NAME \
  CONNECT_DESKTOP_NAME \
  NOTIFICATION_TO \
  NOTIFICATION_FROM \
  PAGES_DEPLOY_HOOK \
  IMAGE_SYNC_URL \
  CRAWL_SECRET \
  POSTMARK_API_TOKEN \
  POSTMARK_MESSAGE_STREAM \
  RESEND_API_KEY

# ─── workers/internal/.dev.vars ──────────────────────────────────────
write_dev_vars "$REPO_ROOT/workers/internal/.dev.vars" \
  KB_DOMAIN \
  INTERNAL_KB_DOMAIN \
  ADMIN_EMAILS \
  EDITOR_EMAILS \
  VIEWER_EMAILS \
  PAGES_DEPLOY_HOOK \
  BRAND_NAME \
  SITE_TITLE \
  CRAWL_SECRET

# ─── workers/images/.dev.vars ────────────────────────────────────────
write_dev_vars "$REPO_ROOT/workers/images/.dev.vars" \
  IMAGE_DOMAIN \
  SOURCE_IMAGE_CDN \
  ADDITIONAL_IMAGE_SOURCES \
  REVALIDATE_HOURS \
  MAX_CONCURRENT \
  CRAWL_SECRET

# ─── public-kb/.dev.vars ─────────────────────────────────────────────
write_dev_vars "$REPO_ROOT/public-kb/.dev.vars" \
  R2_ACCESS_KEY_ID \
  R2_SECRET_ACCESS_KEY \
  R2_ENDPOINT \
  R2_BUCKET \
  KB_DOMAIN_URL \
  HUGO_TITLE \
  HUGO_PARAMS_DESCRIPTION \
  HUGO_PARAMS_COMPANYNAME \
  HUGO_PARAMS_COMPANYURL \
  HUGO_PARAMS_LOGOURL \
  HUGO_PARAMS_INTERNALKBURL \
  HUGO_PARAMS_MANAGERPORTALURL \
  HUGO_PARAMS_BILLINGPORTALURL \
  HUGO_PARAMS_STATUSURL

echo ""
echo "Done. All .dev.vars files written."
echo "Run 'bash scripts/push-vars.sh' to push non-secret vars to Cloudflare."
